### ISSUE TITLE
remove panics

### ISSUE THREAD

**Issue by savelyev-an** [flant/negentropy#405]
### Use case. Why is this important?
There are some place in vault-plugins which can produce panic.
At the real environment this can cause unavailability of service for very long periods

### Proposed Solution
- [x] Add checking for prohibiting panics except tests and special marked places (which cant't broke the system)
- [x] Find all places where panic is used
- [x] Analyse and mark "special" cases
- [x] Fix others panics (remove them in right way)
- [ ] Add checking valid "special" cases to review check-list 

### Additional Information

No response

**Comment by savelyev-an** [comment]
panic prohibited for files at: vault_plugins/* 
except:
1) files: *_test.go
2) files at full_path of which is */tests/*
and if code line with panic ends with:
// nolint:panic_check

**Comment by vmrm** [comment]
We need to add bash script with grep to action with a new step like "find_panics" https://github.com/flant/negentropy/blob/main/.github/workflows/plugins.yaml
After that we need to test it on main - it will alert, and there will be no alerts on 405-remove-panics
